# Generated by Django 4.2.13 on 2026-08-15 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة (مُثبَّت)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('production_date', models.DateField(verbose_name='تاريخ الإنتاج')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='ملغى')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_entries', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_entries', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.productionstage', verbose_name='المرحلة')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.productvariant', verbose_name='نوع المنتج')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='workers.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'سجل إنتاج',
                'verbose_name_plural': 'سجلات الإنتاج',
                'ordering': ['-production_date', '-created_at'],
                'indexes': [models.Index(fields=['variant', 'stage'], name='production__variant_0a999a_idx'), models.Index(fields=['worker', 'production_date'], name='production__worker__0333c0_idx'), models.Index(fields=['production_date'], name='production__product_e86d52_idx'), models.Index(fields=['is_cancelled'], name='production__is_canc_77a342_idx')],
            },
        ),
    ]
