# Generated by Django 4.2.13 on 2026-08-19 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='entered_by_worker',
            field=models.BooleanField(default=False, verbose_name='إدخال ذاتي بواسطة العامل'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
    ]
