# Generated by Django 4.2.13 on 2026-08-15 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود العميل')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صحيح.', regex='^\\+?[0-9\\s\\-]{7,20}$')], verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'لون',
                'verbose_name_plural': 'الألوان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مرحلة الإنتاج',
                'verbose_name_plural': 'مراحل الإنتاج',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='المقاس')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='كود الموديل')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الموديل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_models', to='catalog.client', verbose_name='العميل')),
                ('colors', models.ManyToManyField(blank=True, to='catalog.color', verbose_name='الألوان')),
                ('sizes', models.ManyToManyField(blank=True, to='catalog.size', verbose_name='المقاسات')),
            ],
            options={
                'verbose_name': 'موديل منتج',
                'verbose_name_plural': 'موديلات المنتجات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='كود المنتج (SKU)')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المخططة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color', verbose_name='اللون')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.productmodel', verbose_name='الموديل')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size', verbose_name='المقاس')),
            ],
            options={
                'verbose_name': 'نوع المنتج',
                'verbose_name_plural': 'أنواع المنتجات',
                'ordering': ['product_model', 'color__name', 'size__sort_order'],
                'unique_together': {('product_model', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductModelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_stages', to='catalog.productmodel', verbose_name='الموديل')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_configs', to='catalog.productionstage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'مرحلة الموديل',
                'verbose_name_plural': 'مراحل الموديل',
                'ordering': ['sort_order', 'stage__sort_order'],
                'unique_together': {('product_model', 'stage')},
            },
        ),
    ]
