# Generated by Django 4.2.13 on 2026-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='نوع الموديل'),
        ),
    ]
