# Generated by Django 4.2.13 on 2026-08-15 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم العامل')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صحيح.', regex='^\\+?[0-9\\s\\-]{7,20}$')], verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('stages', models.ManyToManyField(blank=True, related_name='workers', to='catalog.productionstage', verbose_name='المراحل المسندة')),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العمال',
                'ordering': ['name'],
            },
        ),
    ]
