# Generated by Django 4.2.13 on 2026-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('otp_hash', models.CharField(max_length=64, verbose_name='OTP (مُجزَّأ)')),
                ('entity_type', models.CharField(choices=[('client', 'عميل'), ('worker', 'عامل')], max_length=10, verbose_name='نوع الكيان')),
                ('entity_id', models.PositiveIntegerField(verbose_name='معرف الكيان')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل OTP',
                'verbose_name_plural': 'سجلات OTP',
                'indexes': [models.Index(fields=['phone', 'is_used', 'expires_at'], name='notificatio_phone_e2c716_idx')],
            },
        ),
    ]
