# Generated by Django 4.2.13 on 2026-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='رمز الدخول')),
                ('entity_type', models.CharField(max_length=10, verbose_name='نوع الكيان')),
                ('entity_id', models.PositiveIntegerField(verbose_name='معرف الكيان')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رمز دخول سريع',
                'verbose_name_plural': 'رموز الدخول السريع',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True, verbose_name='معرف المحادثة Chat ID')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='رقم الهاتف المسجل')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('entity_type', models.CharField(blank=True, choices=[('client', 'عميل'), ('worker', 'عامل'), ('admin', 'إدارة')], max_length=10, verbose_name='نوع الحساب')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكيان')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='موثق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ملف تليجرام',
                'verbose_name_plural': 'ملفات تليجرام',
            },
        ),
    ]
