# Generated by Django 4.2.13 on 2026-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_magiclogintoken_telegramprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRecord',
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('worker', 'عامل'), ('admin', 'إدارة')], max_length=10, verbose_name='نوع الحساب'),
        ),
    ]
